<?php

namespace AppBundle\Repository;

/**
 * ClienteEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteEmailRepository extends \Doctrine\ORM\EntityRepository
{
}
