<?php

namespace AppBundle\Repository;

/**
 * faqtiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class faqtiRepository extends \Doctrine\ORM\EntityRepository
{
}
